---
title: "Can the number of cat adoptions predict the volume of traffic?"
output: html_notebook
---

_This is a short introductory example of using R that demonstrates simple processes for cleaning and visualizing data and basic statistical analysis. This report was generated using R Markdown Notebook. In no way should the objective of this example be taken seriously, nor do they reflect the views of the instructors or organization sponsors of this course._

# Objective
The feline species are found everywhere in urban areas. Although the vast population of felines do not have "thumbs" to manipulate a steering wheel, increasing research and developement of autonomous vehicles might render their anatomical barrier moot. In preparation of the eventual takeover of autonomous vehicles do we see their infilitration to human households increasing? If so, we first must investigate if there's any relationship between the number of cat adoptions with volume of traffic.

# Methods & Results
## Data sources

## Data cleanup

```{r libraries}
library(tidyverse)
library(lubridate)
```

## Data visualization

## Statistics

# Conclusions